version: '3.9'
services:
  test-db:
    image: postgres:12
    container_name: hw10_container
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=demoDB

    ports:
      - "5430:5432"
