version: '3.9'
services:
  test-db:
    image: postgres:latest
    container_name: hw09_container
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=demoDB

    ports:
      - "5430:5432"
